### ISSUE TITLE
Faster download time?

### ISSUE THREAD

**Issue by grayxr** [gregoiresage/pebble-image-viewer#3]
Hi, I was wondering if I could somehow speed up the time it takes to download an image from a URL? I was thinking if there was a URL parameter to convert the image width to the Pebble screen's max  width dimension and then decode that converted(?) image on the Pebble screen?

**Comment by gregoiresage** [comment]
Hi James, the original image is already resized before being sent to the
watch. But if your original image is big, I can't do anything to speed up
the download

**Comment by grayxr** [comment]
Thanks anyway!
